--- #YAML:1.0
name:                   App-Maisha-Plugin-PingFM
version:                0.04
abstract:               A Maisha plugin for ping.fm
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                     5.006
  App::Maisha:              0.06
  Class::Accessor::Fast:    0
  Net::PingFM:              0
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Test::More:               0.47

provides:
  App::Maisha::Plugin::PingFM:
    file: lib/App/Maisha/Plugin/PingFM.pm
    version: 0.04

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=app-maisha-plugin-pingfm
  repository: http://github.com/barbie/app-maisha-plugin-pingfm

meta-spec:
   version: 1.4
   url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
